import './globals.css'
import { ReduxProvider } from "@/redux";
import React from "react";
import { Notifications } from "@/app/components/notifications";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <ReduxProvider>
            { children }
            <Notifications/>
        </ReduxProvider>
        </body>
        </html>
    )
}
